### ISSUE TITLE
Support more bible-apps 

### ISSUE THREAD

**Issue by schalterDev** [schalterDev/Losungen-Android#9]
for example this apps:
- "My Bible" von Denys Dolganenko (https://play.google.com/store/apps/details?id=ua.mybible)
I asked the developer and he wrote that an external intent is in work but not implemented yet.

- You-Version Bible app
- Logos

**Comment by dlichtistw** [comment]
- and-bible by Martin Denham

**Comment by schalterDev** [comment]
Bibel von Koala sky
